name: GitHub Pages

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install packages
      uses: bahmutov/npm-install@v1

    - name: Lint
      run: yarn lint --no-fix

    - name: Build page
      run: yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        publish_dir: ./dist
        github_token: ${{ secrets.GITHUB_TOKEN }}
